### ISSUE TITLE
支持hook代码与目标方法处于相同DexClassLoader

### ISSUE THREAD

**Issue by rk700** [rk700/YAHFA#29]
设计之初是参考xposed，hook代码采用插件的形式，运行时通过DexClassLoader动态加载。目前基本没有问题

但是现在有些人要把hook代码与app放在一起，这样做目前是不支持的。具体原因和能否解决，还得等将来有时间再去看。用这个issue统一跟踪。

**Comment by rk700** [comment]
开了个新分支 https://github.com/rk700/YAHFA/tree/internalHook

其中就是在demo Application创建时直接进行hook，不使用DexClassLoader。

7.0以上需要改hookMethod的hotness还没有试，但是在x86 avd 5.0-6.0上试验都ok

**Comment by svengong** [comment]
我适配了7.0以上的arm和aarch64，等x86弄完我就提过来

**Comment by liupeng110** [comment]
@rk700  @svengong 
https://github.com/rk700/YAHFA/tree/internalHook
这个分支测试hook系统api是可以的,但是hook其他apk自定义类就不行了
不知道是不是我代码写的有问题一直报classnotfound 
我是直接把internalHook替换项目里yahfa
https://github.com/liupeng110/vhook/

**Comment by liupeng110** [comment]
看到的老哥 加群476086993 开发交流

**Comment by netstu** [comment]
https://github.com/rk700/YAHFA/issues/33

@rk700 一样的问题，我的机器是一加3t 7.1.1

**Comment by cheasonxie** [comment]
魅族7.1.1 hook之后前面几次还可以，到后面提示IncompatibleClassChangeError：
java.lang.IncompatibleClassChangeError: The method ** was expected to be of type static but instead was found to be of type virtual (declaration of **' appears in /data/app/**/base.apk:classes4.dex)

**Comment by conghongjie** [comment]
master分支上直接调用findAndBackupAndHook方法hook FileInputStream.open(String)函数，一秒后出现IllegalAccessError异常：(屡试不爽～)
Process: lab.galaxy.yahfa.demoApp, PID: 24142
java.lang.IllegalAccessError: Method 'void java.io.FileInputStream.open(java.lang.String)' is inaccessible to class 'lab.galaxy.yahfa.demoApp.elvis.Hook_FileInputStream_open' (declaration of 'lab.galaxy.yahfa.demoApp.elvis.Hook_FileInputStream_open' appears in /data/app/lab.galaxy.yahfa.demoApp-1/base.apk)
at lab.galaxy.yahfa.demoApp.elvis.Hook_FileInputStream_open.hook(Hook_FileInputStream_open.java:17)
at java.io.FileInputStream.(FileInputStream.java:146)
at lab.galaxy.yahfa.demoApp.MainActivity.getCPUThreads(MainActivity.java:75)
at lab.galaxy.yahfa.demoApp.MainActivity$1$1.run(MainActivity.java:49)
at java.lang.Thread.run(Thread.java:760)

一、实现hook FileInputStream.open(String)函数：
HookMain.findAndBackupAndHook(
FileInputStream.class,
Hook_FileInputStream_open.methodName,
Hook_FileInputStream_open.methodSig,
getMethod(Hook_FileInputStream_open.class,"hook", Object.class, String.class),
getMethod(Hook_FileInputStream_open.class,"backup", Object.class, String.class)
);

public static String className = "java.io.FileInputStream";
public static String methodName = "open";
public static String methodSig = "(Ljava/lang/String;)V";
public static void hook(Object thiz, String name) {
    Log.e("Elvis","FileInputStream.open start:"+System.currentTimeMillis() + name);
    backup(thiz, name);
    Log.e("Elvis","FileInputStream.open end:"+System.currentTimeMillis());
}
public static void backup(Object thiz, String name) {
    Log.d("Elvis", "FileInputStream.open 这个日志出现了就爆炸了");
}
二、经验证：
在master分支上，用dex的方式hook，无异常
在master分支上，直接调用findAndBackupAndHook的方式hook，有异常
在internalHook分支上，直接调用findAndBackupAndHook的方式hook，无异常

可否解决一下我的疑惑～～
