### ISSUE TITLE
先pendding

### ISSUE THREAD

**Issue by lefu999** [rk700/YAHFA#53]
05-15 16:06:51.576  3596  3596 D AndroidRuntime: Shutting down VM
05-15 16:06:51.576  3596  3596 E AndroidRuntime: FATAL EXCEPTION: main
05-15 16:06:51.576  3596  3596 E AndroidRuntime: Process: com.pingan.lifeinsurance, PID: 3596
05-15 16:06:51.576  3596  3596 E AndroidRuntime: java.lang.NoSuchMethodError: No static method backup(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;II)Z in class LBudHook/GenedClass_0; or its super classes (declaration of 'BudHook.GenedClass_0' appears in /data/data/io.virtualapp/files/BudHook1.dex)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at BudHook.GenedClass_0.replace(Unknown Source:88)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at android.hardware.SensorManager.registerListener(SensorManager.java:817)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at android.hardware.SensorManager.registerListener(SensorManager.java:724)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.business.activities.oldactivities.healthwalk.activity.ae.a(SourceFile:111)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.u.b(SourceFile:54)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.u.a(SourceFile:48)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.ak.a(SourceFile:129)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.ak.c(SourceFile:119)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.common.base.a.e.a(SourceFile:40)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.common.base.a.h.a(SourceFile:123)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.pingan.lifeinsurance.common.base.AppContext.onCreate(SourceFile:69)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.secneo.apkwrapper.ApplicationWrapper.onCreate(ApplicationTemplate.java:47)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:226)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:149)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:334)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:123)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6518)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-15 16:06:51.576  3596  3596 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-15 16:06:51.577  3596  3596 E uncaught: java.lang.NoSuchMethodError: No static method backup(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;II)Z in class LBudHook/GenedClass_0; or its super classes (declaration of 'BudHook.GenedClass_0' appears in /data/data/io.virtualapp/files/BudHook1.dex)
05-15 16:06:51.577  3596  3596 E uncaught: 	at BudHook.GenedClass_0.replace(Unknown Source:88)
05-15 16:06:51.577  3596  3596 E uncaught: 	at android.hardware.SensorManager.registerListener(SensorManager.java:817)
05-15 16:06:51.577  3596  3596 E uncaught: 	at android.hardware.SensorManager.registerListener(SensorManager.java:724)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.business.activities.oldactivities.healthwalk.activity.ae.a(SourceFile:111)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.u.b(SourceFile:54)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.u.a(SourceFile:48)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.ak.a(SourceFile:129)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.basic.initialize.setupcenter.ak.c(SourceFile:119)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.common.base.a.e.a(SourceFile:40)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.common.base.a.h.a(SourceFile:123)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.pingan.lifeinsurance.common.base.AppContext.onCreate(SourceFile:69)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.secneo.apkwrapper.ApplicationWrapper.onCreate(ApplicationTemplate.java:47)
05-15 16:06:51.577  3596  3596 E uncaught: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:226)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:149)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:334)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:123)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
05-15 16:06:51.577  3596  3596 E uncaught: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-15 16:06:51.577  3596  3596 E uncaught: 	at android.os.Looper.loop(Looper.java:164)
05-15 16:06:51.577  3596  3596 E uncaught: 	at android.app.ActivityThread.main(ActivityThread.java:6518)
05-15 16:06:51.577  3596  3596 E uncaught: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-15 16:06:51.577  3596  3596 E uncaught: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

同样的代码在6.0上是正常的

**Comment by rk700** [comment]
提示没找到method，估计和你的classloader有关
